version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - PORT
      - SECRET_AUTH_KEY
      - APP_MODE
      - HIDE_POST_ENDPOINTS
      - DATABASE_URL
