version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3001"
    environment:
      - PORT
      - SECRET_AUTH_KEY
      - APP_MODE
      - HIDE_POST_ENDPOINTS
      - DATABASE_URL
    networks:
      - db_postgres

networks:
  db_postgres:
    external: true
